#define ACCESS_REGION_NONE -1
#define ACCESS_REGION_ALL 0
#define ACCESS_REGION_COUNCIL 1
#define ACCESS_REGION_BANK 2
#define ACCESS_REGION_NANOTRASEN 3
#define ACCESS_REGION_CIVILIAN 4

// Keep those two up to date
#define ACCESS_REGION_MIN 1
#define ACCESS_REGION_MAX 4